### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mustang164**
let me know if any change needed

### CODE REVIEW

**Comment by JoshStrobl** [comment]
1. Where is this image from?
2. What is it licensed under?
3. It should be ran through GIMP, saved as a JPG and compressed slightly. Shouldn't be a 6.3MB png.
4. You didn't provide a name for it. Untitled desktop 50 isn't really acceptable :P

**Comment by mustang164** [comment]
> 1. Where is this image from?
> 2. What is it licensed under?
> 3. It should be ran through GIMP, saved as a JPG and compressed slightly. Shouldn't be a 6.3MB png.
> 4. You didn't provide a name for it. Untitled desktop 50 isn't really acceptable :P

1. i created it in gimp
2. since i created for anyone to use i dont think i need to licence it
3. sure will make it jpg and compress it
4. i will change

**Comment by mustang164** [comment]
just a reminder i fixed issues and re-uploaded

**Comment by JoshStrobl** [comment]
Do you not have any more inspirational name for it than solus-desktop-1? :P

**Comment by JoshStrobl** [comment]
Wow an actual name xD Thanks!

**Pull request merged**
